# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
name = "Posts"
pageRef = "/posts"
weight = 10

#[[main]]
#  name = "Parent"
#  weight = 20

#[[main]]
#  name = "example sub-menu 1"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

[[main]]
name = "Tags"
pageRef = "/tags"
weight = 30

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20

[[footer]]
identifier = "email"
pre = "email"
title = "Email"
url = "mailto:toxe@toxe.net"
weight = 10

[[footer]]
identifier = "github"
pre = "github"
title = "GitHub"
url = "https://github.com/Toxe"
weight = 20

[[footer]]
identifier = "bluesky"
pre = "bluesky"
title = "Bluesky"
url = "https://bsky.app/profile/sirtoxe.bsky.social"
weight = 30

[[footer]]
identifier = "reddit"
pre = "reddit"
title = "Reddit"
url = "https://reddit.com/user/SirToxe"
weight = 40

[[footer]]
identifier = "itch-io"
pre = "itch-io"
title = "itch.io"
url = "https://toxe.itch.io"
weight = 50

[[footer]]
identifier = "youtube"
pre = "youtube"
title = "YouTube"
url = "https://www.youtube.com/@SirToxe"
weight = 60

[[footer]]
name = "About/Contact/Legal"
pageRef = "/about"
weight = 110

[[footer]]
name = "🇩🇪 Impressum"
pageRef = "/impressum"
weight = 120

[[footer]]
name = "🇩🇪 Datenschutzerklärung"
pageRef = "/datenschutzerklärung"
weight = 130
